import { Component } from '@angular/core';
import {ActionSheetController, Events, IonicPage, NavController, NavParams, ToastController} from 'ionic-angular';
import {Storage} from "@ionic/storage";
import moment from 'moment';

/**
 * Generated class for the SuggestionsPage page.
 *
 * See https://ionicframework.com/docs/components/#navigation for more info on
 * Ionic pages and navigation.
 */
@IonicPage()
@Component({
  selector: 'page-suggestions',
  templateUrl: 'suggestions.html',
})
export class SuggestionsPage {

  topic;
  passages;
  verses;
  salvation = [
    "Psalm 40:1-5: To the choirmaster. A Psalm of David.<br/>[1] I waited patiently for the LORD;<br/>    he inclined to me and heard my cry.<br/>[2] He drew me up from the pit of destruction,<br/>    out of the miry bog,<br/>and set my feet upon a rock,<br/>    making my steps secure.<br/>[3] He put a new song in my mouth,<br/>    a song of praise to our God.<br/>Many will see and fear,<br/>    and put their trust in the LORD.<br/>[4] Blessed is the man who makes<br/>    the LORD his trust,<br/>who does not turn to the proud,<br/>    to those who go astray after a lie!<br/>[5] You have multiplied, O LORD my God,<br/>    your wondrous deeds and your thoughts toward us;<br/>    none can compare with you!<br/>I will proclaim and tell of them,<br/>    yet they are more than can be told.",
    "Isaiah 53:3-12: [3] He was despised and rejected by men,<br/>    a man of sorrows and acquainted with grief;<br/>and as one from whom men hide their faces<br/>    he was despised, and we esteemed him not.<br/>[4] Surely he has borne our griefs<br/>    and carried our sorrows;<br/>yet we esteemed him stricken,<br/>    smitten by God, and afflicted.<br/>[5] But he was pierced for our transgressions;<br/>    he was crushed for our iniquities;<br/>upon him was the chastisement that brought us peace,<br/>    and with his wounds we are healed.<br/>[6] All we like sheep have gone astray;<br/>    we have turned—every one—to his own way;<br/>and the LORD has laid on him<br/>    the iniquity of us all.<br/>[7] He was oppressed, and he was afflicted,<br/>    yet he opened not his mouth;<br/>like a lamb that is led to the slaughter,<br/>    and like a sheep that before its shearers is silent,<br/>    so he opened not his mouth.<br/>[8] By oppression and judgment he was taken away;<br/>    and as for his generation, who considered<br/>that he was cut off out of the land of the living,<br/>    stricken for the transgression of my people?<br/>[9] And they made his grave with the wicked<br/>    and with a rich man in his death,<br/>although he had done no violence,<br/>    and there was no deceit in his mouth.<br/>[10] Yet it was the will of the LORD to crush him;<br/>    he has put him to grief;<br/>when his soul makes an offering for guilt,<br/>    he shall see his offspring; he shall prolong his days;<br/>the will of the LORD shall prosper in his hand.<br/>[11] Out of the anguish of his soul he shall see and be satisfied;<br/>by his knowledge shall the righteous one, my servant,<br/>    make many to be accounted righteous,<br/>    and he shall bear their iniquities.<br/>[12] Therefore I will divide him a portion with the many,<br/>    and he shall divide the spoil with the strong,<br/>because he poured out his soul to death<br/>    and was numbered with the transgressors;<br/>yet he bore the sin of many,<br/>    and makes intercession for the transgressors.",
    "Isaiah 61:10: [10] I will greatly rejoice in the LORD;<br/>    my soul shall exult in my God,<br/>for he has clothed me with the garments of salvation;<br/>    he has covered me with the robe of righteousness,<br/>as a bridegroom decks himself like a priest with a beautiful headdress,<br/>    and as a bride adorns herself with her jewels.",
    "Luke 1:68-75: [68] “Blessed be the Lord God of Israel,<br/>    for he has visited and redeemed his people<br/>[69] and has raised up a horn of salvation for us<br/>    in the house of his servant David,<br/>[70] as he spoke by the mouth of his holy prophets from of old,<br/>[71] that we should be saved from our enemies<br/>    and from the hand of all who hate us;<br/>[72] to show the mercy promised to our fathers<br/>    and to remember his holy covenant,<br/>[73] the oath that he swore to our father Abraham, to grant us<br/>[74]     that we, being delivered from the hand of our enemies,<br/>might serve him without fear,<br/>[75]     in holiness and righteousness before him all our days.",
    "Romans 3:21-26: [21] But now the righteousness of God has been manifested apart from the law, although the Law and the Prophets bear witness to it—[22] the righteousness of God through faith in Jesus Christ for all who believe. For there is no distinction: [23] for all have sinned and fall short of the glory of God, [24] and are justified by his grace as a gift, through the redemption that is in Christ Jesus, [25] whom God put forward as a propitiation by his blood, to be received by faith. This was to show God's righteousness, because in his divine forbearance he had passed over former sins. [26] It was to show his righteousness at the present time, so that he might be just and the justifier of the one who has faith in Jesus.",
    "Ephesians 2:8: [8] For by grace you have been saved through faith. And this is not your own doing; it is the gift of God,",
    "Colossians 1:19-23: [19] For in him all the fullness of God was pleased to dwell, [20] and through him to reconcile to himself all things, whether on earth or in heaven, making peace by the blood of his cross.<br/>[21] And you, who once were alienated and hostile in mind, doing evil deeds, [22] he has now reconciled in his body of flesh by his death, in order to present you holy and blameless and above reproach before him, [23] if indeed you continue in the faith, stable and steadfast, not shifting from the hope of the gospel that you heard, which has been proclaimed in all creation under heaven, and of which I, Paul, became a minister.",
    "Hebrews 2:14-15: [14] Since therefore the children share in flesh and blood, he himself likewise partook of the same things, that through death he might destroy the one who has the power of death, that is, the devil, [15] and deliver all those who through fear of death were subject to lifelong slavery.",
    "Hebrews 7:25: [25] Consequently, he is able to save to the uttermost those who draw near to God through him, since he always lives to make intercession for them.",
    "1 Peter 1:3-5: [3] Blessed be the God and Father of our Lord Jesus Christ! According to his great mercy, he has caused us to be born again to a living hope through the resurrection of Jesus Christ from the dead, [4] to an inheritance that is imperishable, undefiled, and unfading, kept in heaven for you, [5] who by God's power are being guarded through faith for a salvation ready to be revealed in the last time.",
    "1 Peter 2:24: [24] He himself bore our sins in his body on the tree, that we might die to sin and live to righteousness. By his wounds you have been healed.",
    "1 Peter 3:18: [18] For Christ also suffered once for sins, the righteous for the unrighteous, that he might bring us to God, being put to death in the flesh but made alive in the spirit,"
  ];
  grace = [
    "Deuteronomy 7:6-8: [6] \"For you are a people holy to the LORD your God. The LORD your God has chosen you to be a people for his treasured possession, out of all the peoples who are on the face of the earth. [7] It was not because you were more in number than any other people that the LORD set his love on you and chose you, for you were the fewest of all peoples, [8] but it is because the LORD loves you and is keeping the oath that he swore to your fathers, that the LORD has brought you out with a mighty hand and redeemed you from the house of slavery, from the hand of Pharaoh king of Egypt.",
    "Psalm 103:10-12: [10] He does not deal with us according to our sins,<br/>    nor repay us according to our iniquities.<br/>[11] For as high as the heavens are above the earth,<br/>    so great is his steadfast love toward those who fear him;<br/>[12] as far as the east is from the west,<br/>    so far does he remove our transgressions from us.",
    "Isaiah 40:1-2: [1] Comfort, comfort my people, says your God.<br/>[2] Speak tenderly to Jerusalem,<br/>    and cry to her<br/>that her warfare is ended,<br/>    that her iniquity is pardoned,<br/>that she has received from the LORD's hand<br/>    double for all her sins.",
    "Mark 10:45: [45] For even the Son of Man came not to be served but to serve, and to give his life as a ransom for many.\"",
    "Romans 5:8: [8] but God shows his love for us in that while we were still sinners, Christ died for us.",
    "Romans 8:1: [1] There is therefore now no condemnation for those who are in Christ Jesus.",
    "Romans 8:32-34: [32] He who did not spare his own Son but gave him up for us all, how will he not also with him graciously give us all things? [33] Who shall bring any charge against God's elect? It is God who justifies. [34] Who is to condemn? Christ Jesus is the one who died—more than that, who was raised—who is at the right hand of God, who indeed is interceding for us.",
    "2 Corinthians 5:21: [21] For our sake he made him to be sin who knew no sin, so that in him we might become the righteousness of God.",
    "2 Corinthians 8:9: [9] For you know the grace of our Lord Jesus Christ, that though he was rich, yet for your sake he became poor, so that you by his poverty might become rich.",
    "Galatians 3:13-14: [13] Christ redeemed us from the curse of the law by becoming a curse for us—for it is written, \"Cursed is everyone who is hanged on a tree\"—[14] so that in Christ Jesus the blessing of Abraham might come to the Gentiles, so that we might receive the promised Spirit through faith.",
    "Ephesians 1:7: [7] In him we have redemption through his blood, the forgiveness of our trespasses, according to the riches of his grace,",
    "Ephesians 2:1-9: [1] And you were dead in the trespasses and sins [2] in which you once walked, following the course of this world, following the prince of the power of the air, the spirit that is now at work in the sons of disobedience—[3] among whom we all once lived in the passions of our flesh, carrying out the desires of the body and the mind, and were by nature children of wrath, like the rest of mankind. [4] But God, being rich in mercy, because of the great love with which he loved us, [5] even when we were dead in our trespasses, made us alive together with Christ—by grace you have been saved—[6] and raised us up with him and seated us with him in the heavenly places in Christ Jesus, [7] so that in the coming ages he might show the immeasurable riches of his grace in kindness toward us in Christ Jesus. [8] For by grace you have been saved through faith. And this is not your own doing; it is the gift of God, [9] not a result of works, so that no one may boast.",
    "Colossians 1:13-14: [13] He has delivered us from the domain of darkness and transferred us to the kingdom of his beloved Son, [14] in whom we have redemption, the forgiveness of sins.<br/>,Colossians 2:13-14: [13] And you, who were dead in your trespasses and the uncircumcision of your flesh, God made alive together with him, having forgiven us all our trespasses, [14] by canceling the record of debt that stood against us with its legal demands. This he set aside, nailing it to the cross.",
    "Titus 2:11: [11] For the grace of God has appeared, bringing salvation for all people,",
    "Titus 3:3-7: [3] For we ourselves were once foolish, disobedient, led astray, slaves to various passions and pleasures, passing our days in malice and envy, hated by others and hating one another. [4] But when the goodness and loving kindness of God our Savior appeared, [5] he saved us, not because of works done by us in righteousness, but according to his own mercy, by the washing of regeneration and renewal of the Holy Spirit, [6] whom he poured out on us richly through Jesus Christ our Savior, [7] so that being justified by his grace we might become heirs according to the hope of eternal life."
  ];
  confession = [
    "Psalm 25:6-11: [6] Remember your mercy, O LORD, and your steadfast love,<br/>    for they have been from of old.<br/>[7] Remember not the sins of my youth or my transgressions;<br/>    according to your steadfast love remember me,<br/>    for the sake of your goodness, O LORD!<br/>[8] Good and upright is the LORD;<br/>    therefore he instructs sinners in the way.<br/>[9] He leads the humble in what is right,<br/>    and teaches the humble his way.<br/>[10] All the paths of the LORD are steadfast love and faithfulness,<br/>    for those who keep his covenant and his testimonies.<br/>[11] For your name's sake, O LORD,<br/>    pardon my guilt, for it is great.",
    "Psalm 32:1-5: A Maskil of David.<br/>[1] Blessed is the one whose transgression is forgiven,<br/>    whose sin is covered.<br/>[2] Blessed is the man against whom the LORD counts no iniquity,<br/>    and in whose spirit there is no deceit.<br/>[3] For when I kept silent, my bones wasted away<br/>    through my groaning all day long.<br/>[4] For day and night your hand was heavy upon me;<br/>    my strength was dried up as by the heat of summer. Selah<br/>[5] I acknowledged my sin to you,<br/>    and I did not cover my iniquity;<br/>I said, \"I will confess my transgressions to the LORD,\"<br/>    and you forgave the iniquity of my sin. Selah",
    "Psalm 51:1-12: To the choirmaster. A Psalm of David, when Nathan the prophet went to him, after he had gone in to Bathsheba.<br/>[1] Have mercy on me, O God,<br/>    according to your steadfast love;<br/>according to your abundant mercy<br/>    blot out my transgressions.<br/>[2] Wash me thoroughly from my iniquity,<br/>    and cleanse me from my sin!<br/>[3] For I know my transgressions,<br/>    and my sin is ever before me.<br/>[4] Against you, you only, have I sinned<br/>    and done what is evil in your sight,<br/>so that you may be justified in your words<br/>    and blameless in your judgment.<br/>[5] Behold, I was brought forth in iniquity,<br/>    and in sin did my mother conceive me.<br/>[6] Behold, you delight in truth in the inward being,<br/>    and you teach me wisdom in the secret heart.<br/>[7] Purge me with hyssop, and I shall be clean;<br/>    wash me, and I shall be whiter than snow.<br/>[8] Let me hear joy and gladness;<br/>    let the bones that you have broken rejoice.<br/>[9] Hide your face from my sins,<br/>    and blot out all my iniquities.<br/>[10] Create in me a clean heart, O God,<br/>    and renew a right spirit within me.<br/>[11] Cast me not away from your presence,<br/>    and take not your Holy Spirit from me.<br/>[12] Restore to me the joy of your salvation,<br/>    and uphold me with a willing spirit.",
    "Psalm 130: A Song of Ascents.<br/>[1] Out of the depths I cry to you, O LORD!<br/>[2]     O Lord, hear my voice!<br/>Let your ears be attentive<br/>    to the voice of my pleas for mercy!<br/>[3] If you, O LORD, should mark iniquities,<br/>    O Lord, who could stand?<br/>[4] But with you there is forgiveness,<br/>    that you may be feared.<br/>[5] I wait for the LORD, my soul waits,<br/>    and in his word I hope;<br/>[6] my soul waits for the Lord<br/>    more than watchmen for the morning,<br/>    more than watchmen for the morning.<br/>[7] O Israel, hope in the LORD!<br/>    For with the LORD there is steadfast love,<br/>    and with him is plentiful redemption.<br/>[8] And he will redeem Israel<br/>    from all his iniquities.",
    "Jeremiah 14:7: [7] \"Though our iniquities testify against us,<br/>    act, O LORD, for your name's sake;<br/>for our backslidings are many;<br/>    we have sinned against you.",
    "1 John 1:8-9: [8] If we say we have no sin, we deceive ourselves, and the truth is not in us. [9] If we confess our sins, he is faithful and just to forgive us our sins and to cleanse us from all unrighteousness."
  ];
  suffering = [
    "Psalm 6: To the choirmaster: with stringed instruments; according to The Sheminith. A Psalm of David.<br/>[1] O LORD, rebuke me not in your anger,<br/>    nor discipline me in your wrath.<br/>[2] Be gracious to me, O LORD, for I am languishing;<br/>    heal me, O LORD, for my bones are troubled.<br/>[3] My soul also is greatly troubled.<br/>    But you, O LORD—how long?<br/>[4] Turn, O LORD, deliver my life;<br/>    save me for the sake of your steadfast love.<br/>[5] For in death there is no remembrance of you;<br/>    in Sheol who will give you praise?<br/>[6] I am weary with my moaning;<br/>    every night I flood my bed with tears;<br/>    I drench my couch with my weeping.<br/>[7] My eye wastes away because of grief;<br/>    it grows weak because of all my foes.<br/>[8] Depart from me, all you workers of evil,<br/>    for the LORD has heard the sound of my weeping.<br/>[9] The LORD has heard my plea;<br/>    the LORD accepts my prayer.<br/>[10] All my enemies shall be ashamed and greatly troubled;<br/>    they shall turn back and be put to shame in a moment.",
    "Psalm 13: To the choirmaster. A Psalm of David.<br/>[1] How long, O LORD? Will you forget me forever?<br/>    How long will you hide your face from me?<br/>[2] How long must I take counsel in my soul<br/>    and have sorrow in my heart all the day?<br/>How long shall my enemy be exalted over me?<br/>[3] Consider and answer me, O LORD my God;<br/>    light up my eyes, lest I sleep the sleep of death,<br/>[4] lest my enemy say, \"I have prevailed over him,\"<br/>    lest my foes rejoice because I am shaken.<br/>[5] But I have trusted in your steadfast love;<br/>    my heart shall rejoice in your salvation.<br/>[6] I will sing to the LORD,<br/>    because he has dealt bountifully with me.",
    "Psalm 30:5: [5] For his anger is but for a moment,<br/>    and his favor is for a lifetime.<br/>Weeping may tarry for the night,<br/>    but joy comes with the morning.",
    "Psalm 34:18-19: [18] The LORD is near to the brokenhearted<br/>    and saves the crushed in spirit.<br/>[19] Many are the afflictions of the righteous,<br/>    but the LORD delivers him out of them all.",
    "Psalm 73:21-28: [21] When my soul was embittered,<br/>    when I was pricked in heart,<br/>[22] I was brutish and ignorant;<br/>    I was like a beast toward you.<br/>[23] Nevertheless, I am continually with you;<br/>    you hold my right hand.<br/>[24] You guide me with your counsel,<br/>    and afterward you will receive me to glory.<br/>[25] Whom have I in heaven but you?<br/>    And there is nothing on earth that I desire besides you.<br/>[26] My flesh and my heart may fail,<br/>    but God is the strength of my heart and my portion forever.<br/>[27] For behold, those who are far from you shall perish;<br/>    you put an end to everyone who is unfaithful to you.<br/>[28] But for me it is good to be near God;<br/>    I have made the Lord GOD my refuge,<br/>    that I may tell of all your works.",
    "Matthew 10:28-31: [28] And do not fear those who kill the body but cannot kill the soul. Rather fear him who can destroy both soul and body in hell. [29] Are not two sparrows sold for a penny? And not one of them will fall to the ground apart from your Father. [30] But even the hairs of your head are all numbered. [31] Fear not, therefore; you are of more value than many sparrows.",
    "John 16:20-22: [20] Truly, truly, I say to you, you will weep and lament, but the world will rejoice. You will be sorrowful, but your sorrow will turn into joy. [21] When a woman is giving birth, she has sorrow because her hour has come, but when she has delivered the baby, she no longer remembers the anguish, for joy that a human being has been born into the world. [22] So also you have sorrow now, but I will see you again, and your hearts will rejoice, and no one will take your joy from you.",
    "Romans 5:3-5: [3] Not only that, but we rejoice in our sufferings, knowing that suffering produces endurance, [4] and endurance produces character, and character produces hope, [5] and hope does not put us to shame, because God's love has been poured into our hearts through the Holy Spirit who has been given to us.",
    "Romans 8:18: [18] For I consider that the sufferings of this present time are not worth comparing with the glory that is to be revealed to us.",
    "2 Corinthians 12:8-10: [8] Three times I pleaded with the Lord about this, that it should leave me. [9] But he said to me, \"My grace is sufficient for you, for my power is made perfect in weakness.\" Therefore I will boast all the more gladly of my weaknesses, so that the power of Christ may rest upon me. [10] For the sake of Christ, then, I am content with weaknesses, insults, hardships, persecutions, and calamities. For when I am weak, then I am strong.",
    "1 Peter 4:12-14: [12] Beloved, do not be surprised at the fiery trial when it comes upon you to test you, as though something strange were happening to you. [13] But rejoice insofar as you share Christ's sufferings, that you may also rejoice and be glad when his glory is revealed. [14] If you are insulted for the name of Christ, you are blessed, because the Spirit of glory and of God rests upon you.",
    "1 Peter 5:10: [10] And after you have suffered a little while, the God of all grace, who has called you to his eternal glory in Christ, will himself restore, confirm, strengthen, and establish you."
  ];
  motivationToHoliness = [
    "Proverbs 5:3-14: [3] For the lips of a forbidden woman drip honey,<br/>    and her speech is smoother than oil,<br/>[4] but in the end she is bitter as wormwood,<br/>    sharp as a two-edged sword.<br/>[5] Her feet go down to death;<br/>    her steps follow the path to Sheol;<br/>[6] she does not ponder the path of life;<br/>    her ways wander, and she does not know it.<br/>[7] And now, O sons, listen to me,<br/>    and do not depart from the words of my mouth.<br/>[8] Keep your way far from her,<br/>    and do not go near the door of her house,<br/>[9] lest you give your honor to others<br/>    and your years to the merciless,<br/>[10] lest strangers take their fill of your strength,<br/>    and your labors go to the house of a foreigner,<br/>[11] and at the end of your life you groan,<br/>    when your flesh and body are consumed,<br/>[12] and you say, \"How I hated discipline,<br/>    and my heart despised reproof!<br/>[13] I did not listen to the voice of my teachers<br/>    or incline my ear to my instructors.<br/>[14] I am at the brink of utter ruin<br/>    in the assembled congregation.\"",
    "Mark 9:43: [43] And if your hand causes you to sin, cut it off. It is better for you to enter life crippled than with two hands to go to hell, to the unquenchable fire.",
    "Romans 6:1-7: [1] What shall we say then? Are we to continue in sin that grace may abound? [2] By no means! How can we who died to sin still live in it? [3] Do you not know that all of us who have been baptized into Christ Jesus were baptized into his death? [4] We were buried therefore with him by baptism into death, in order that, just as Christ was raised from the dead by the glory of the Father, we too might walk in newness of life.<br/>[5] For if we have been united with him in a death like his, we shall certainly be united with him in a resurrection like his. [6] We know that our old self was crucified with him in order that the body of sin might be brought to nothing, so that we would no longer be enslaved to sin. [7] For one who has died has been set free from sin.",
    "Romans 8:13-14: [13] For if you live according to the flesh you will die, but if by the Spirit you put to death the deeds of the body, you will live. [14] For all who are led by the Spirit of God are sons of God.",
    "1 Corinthians 6:19-20: [19] Or do you not know that your body is a temple of the Holy Spirit within you, whom you have from God? You are not your own, [20] for you were bought with a price. So glorify God in your body.",
    "1 Thessalonians 4:3-7: [3] For this is the will of God, your sanctification: that you abstain from sexual immorality; [4] that each one of you know how to control his own body in holiness and honor, [5] not in the passion of lust like the Gentiles who do not know God; [6] that no one transgress and wrong his brother in this matter, because the Lord is an avenger in all these things, as we told you beforehand and solemnly warned you. [7] For God has not called us for impurity, but in holiness.",
    "2 Timothy 2:22: [22] So flee youthful passions and pursue righteousness, faith, love, and peace, along with those who call on the Lord from a pure heart.",
    "1 Peter 1:14-19: [14] As obedient children, do not be conformed to the passions of your former ignorance, [15] but as he who called you is holy, you also be holy in all your conduct, [16] since it is written, \"You shall be holy, for I am holy.\" [17] And if you call on him as Father who judges impartially according to each one's deeds, conduct yourselves with fear throughout the time of your exile, [18] knowing that you were ransomed from the futile ways inherited from your forefathers, not with perishable things such as silver or gold, [19] but with the precious blood of Christ, like that of a lamb without blemish or spot."
  ];
  adoption = [
    "Psalm 27:10: [10] For my father and my mother have forsaken me,<br/>    but the LORD will take me in.",
    "Isaiah 49:15-16: [15] \"Can a woman forget her nursing child,<br/>    that she should have no compassion on the son of her womb?<br/>Even these may forget,<br/>    yet I will not forget you.<br/>[16] Behold, I have engraved you on the palms of my hands;<br/>    your walls are continually before me.",
    "Romans 8:14-17: [14] For all who are led by the Spirit of God are sons of God. [15] For you did not receive the spirit of slavery to fall back into fear, but you have received the Spirit of adoption as sons, by whom we cry, \"Abba! Father!\" [16] The Spirit himself bears witness with our spirit that we are children of God, [17] and if children, then heirs—heirs of God and fellow heirs with Christ, provided we suffer with him in order that we may also be glorified with him.",
    "Hebrews 12:5-7: [5] And have you forgotten the exhortation that addresses you as sons?<br/>\"My son, do not regard lightly the discipline of the Lord,<br/>    nor be weary when reproved by him.<br/>[6] For the Lord disciplines the one he loves,<br/>    and chastises every son whom he receives.\"<br/>[7] It is for discipline that you have to endure. God is treating you as sons. For what son is there whom his father does not discipline?",
    "1 John 3:1-2: [1] See what kind of love the Father has given to us, that we should be called children of God; and so we are. The reason why the world does not know us is that it did not know him. [2] Beloved, we are God's children now, and what we will be has not yet appeared; but we know that when he appears we shall be like him, because we shall see him as he is."
  ];
  trustingGod = [
    "Deuteronomy 31:6: [6] Be strong and courageous. Do not fear or be in dread of them, for it is the LORD your God who goes with you. He will not leave you or forsake you.\"",
    "Psalm 46: To the choirmaster. Of the Sons of Korah. According to Alamoth. A Song.<br/>[1] God is our refuge and strength,<br/>    a very present help in trouble.<br/>[2] Therefore we will not fear though the earth gives way,<br/>    though the mountains be moved into the heart of the sea,<br/>[3] though its waters roar and foam,<br/>    though the mountains tremble at its swelling. Selah<br/>[4] There is a river whose streams make glad the city of God,<br/>    the holy habitation of the Most High.<br/>[5] God is in the midst of her; she shall not be moved;<br/>    God will help her when morning dawns.<br/>[6] The nations rage, the kingdoms totter;<br/>    he utters his voice, the earth melts.<br/>[7] The LORD of hosts is with us;<br/>    the God of Jacob is our fortress. Selah<br/>[8] Come, behold the works of the LORD,<br/>    how he has brought desolations on the earth.<br/>[9] He makes wars cease to the end of the earth;<br/>    he breaks the bow and shatters the spear;<br/>    he burns the chariots with fire.<br/>[10] \"Be still, and know that I am God.<br/>    I will be exalted among the nations,<br/>    I will be exalted in the earth!\"<br/>[11] The LORD of hosts is with us;<br/>    the God of Jacob is our fortress. Selah",
    "Proverbs 3:5-6: [5] Trust in the LORD with all your heart,<br/>    and do not lean on your own understanding.<br/>[6] In all your ways acknowledge him,<br/>    and he will make straight your paths.",
    "Jeremiah 9:23-24: [23] Thus says the LORD: \"Let not the wise man boast in his wisdom, let not the mighty man boast in his might, let not the rich man boast in his riches, [24] but let him who boasts boast in this, that he understands and knows me, that I am the LORD who practices steadfast love, justice, and righteousness in the earth. For in these things I delight, declares the LORD.\"",
    "Matthew 6:25-34: [25] \"Therefore I tell you, do not be anxious about your life, what you will eat or what you will drink, nor about your body, what you will put on. Is not life more than food, and the body more than clothing? [26] Look at the birds of the air: they neither sow nor reap nor gather into barns, and yet your heavenly Father feeds them. Are you not of more value than they? [27] And which of you by being anxious can add a single hour to his span of life? [28] And why are you anxious about clothing? Consider the lilies of the field, how they grow: they neither toil nor spin, [29] yet I tell you, even Solomon in all his glory was not arrayed like one of these. [30] But if God so clothes the grass of the field, which today is alive and tomorrow is thrown into the oven, will he not much more clothe you, O you of little faith? [31] Therefore do not be anxious, saying, ‘What shall we eat?’ or ‘What shall we drink?’ or ‘What shall we wear?’ [32] For the Gentiles seek after all these things, and your heavenly Father knows that you need them all. [33] But seek first the kingdom of God and his righteousness, and all these things will be added to you.<br/>[34] \"Therefore do not be anxious about tomorrow, for tomorrow will be anxious for itself. Sufficient for the day is its own trouble.",
    "John 14:27: [27] Peace I leave with you; my peace I give to you. Not as the world gives do I give to you. Let not your hearts be troubled, neither let them be afraid.",
    "John 16:32-33: [32] Behold, the hour is coming, indeed it has come, when you will be scattered, each to his own home, and will leave me alone. Yet I am not alone, for the Father is with me. [33] I have said these things to you, that in me you may have peace. In the world you will have tribulation. But take heart; I have overcome the world.\"",
    "Romans 8:28-31: [28] And we know that for those who love God all things work together for good, for those who are called according to his purpose. [29] For those whom he foreknew he also predestined to be conformed to the image of his Son, in order that he might be the firstborn among many brothers. [30] And those whom he predestined he also called, and those whom he called he also justified, and those whom he justified he also glorified.<br/>[31] What then shall we say to these things? If God is for us, who can be against us?",
    "Philippians 4:6-7: [6] do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God. [7] And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.",
    "Colossians 3:15: [15] And let the peace of Christ rule in your hearts, to which indeed you were called in one body. And be thankful.",
    "Hebrews 6:17-20: [17] So when God desired to show more convincingly to the heirs of the promise the unchangeable character of his purpose, he guaranteed it with an oath, [18] so that by two unchangeable things, in which it is impossible for God to lie, we who have fled for refuge might have strong encouragement to hold fast to the hope set before us. [19] We have this as a sure and steadfast anchor of the soul, a hope that enters into the inner place behind the curtain, [20] where Jesus has gone as a forerunner on our behalf, having become a high priest forever after the order of Melchizedek.",
    "Hebrews 13:5-6: [5] Keep your life free from love of money, and be content with what you have, for he has said, \"I will never leave you nor forsake you.\" [6] So we can confidently say,<br/>\"The Lord is my helper;<br/>    I will not fear;<br/>what can man do to me?\""
  ];
  theGreatnessOfGod = [
    "Psalm 29: A Psalm of David.<br/>[1] Ascribe to the LORD, O heavenly beings,<br/>    ascribe to the LORD glory and strength.<br/>[2] Ascribe to the LORD the glory due his name;<br/>    worship the LORD in the splendor of holiness.<br/>[3] The voice of the LORD is over the waters;<br/>    the God of glory thunders,<br/>    the LORD, over many waters.<br/>[4] The voice of the LORD is powerful;<br/>    the voice of the LORD is full of majesty.<br/>[5] The voice of the LORD breaks the cedars;<br/>    the LORD breaks the cedars of Lebanon.<br/>[6] He makes Lebanon to skip like a calf,<br/>    and Sirion like a young wild ox.<br/>[7] The voice of the LORD flashes forth flames of fire.<br/>[8] The voice of the LORD shakes the wilderness;<br/>    the LORD shakes the wilderness of Kadesh.<br/>[9] The voice of the LORD makes the deer give birth<br/>    and strips the forests bare,<br/>    and in his temple all cry, \"Glory!\"<br/>[10] The LORD sits enthroned over the flood;<br/>    the LORD sits enthroned as king forever.<br/>[11] May the LORD give strength to his people!<br/>    May the LORD bless his people with peace!",
    "Isaiah 40:10-15: [10] Behold, the Lord GOD comes with might,<br/>    and his arm rules for him;<br/>behold, his reward is with him,<br/>    and his recompense before him.<br/>[11] He will tend his flock like a shepherd;<br/>    he will gather the lambs in his arms;<br/>he will carry them in his bosom,<br/>    and gently lead those that are with young.<br/>[12] Who has measured the waters in the hollow of his hand<br/>    and marked off the heavens with a span,<br/>enclosed the dust of the earth in a measure<br/>    and weighed the mountains in scales<br/>    and the hills in a balance?<br/>[13] Who has measured the Spirit of the LORD,<br/>    or what man shows him his counsel?<br/>[14] Whom did he consult,<br/>    and who made him understand?<br/>Who taught him the path of justice,<br/>    and taught him knowledge,<br/>    and showed him the way of understanding?<br/>[15] Behold, the nations are like a drop from a bucket,<br/>    and are accounted as the dust on the scales;<br/>    behold, he takes up the coastlands like fine dust.",
    "Hebrews 1:3-4: [3] He is the radiance of the glory of God and the exact imprint of his nature, and he upholds the universe by the word of his power. After making purification for sins, he sat down at the right hand of the Majesty on high, [4] having become as much superior to angels as the name he has inherited is more excellent than theirs.",
    "Hebrews 4:12-13: [12] For the word of God is living and active, sharper than any two-edged sword, piercing to the division of soul and of spirit, of joints and of marrow, and discerning the thoughts and intentions of the heart. [13] And no creature is hidden from his sight, but all are naked and exposed to the eyes of him to whom we must give account."
  ];
  theKindnessOfGod = [
    "Psalm 36:5-10: [5] Your steadfast love, O LORD, extends to the heavens,<br/>    your faithfulness to the clouds.<br/>[6] Your righteousness is like the mountains of God;<br/>    your judgments are like the great deep;<br/>    man and beast you save, O LORD.<br/>[7] How precious is your steadfast love, O God!<br/>    The children of mankind take refuge in the shadow of your wings.<br/>[8] They feast on the abundance of your house,<br/>    and you give them drink from the river of your delights.<br/>[9] For with you is the fountain of life;<br/>    in your light do we see light.<br/>[10] Oh, continue your steadfast love to those who know you,<br/>    and your righteousness to the upright of heart!",
    "Psalm 139:1-18: To the choirmaster. A Psalm of David.<br/>[1] O LORD, you have searched me and known me!<br/>[2] You know when I sit down and when I rise up;<br/>    you discern my thoughts from afar.<br/>[3] You search out my path and my lying down<br/>    and are acquainted with all my ways.<br/>[4] Even before a word is on my tongue,<br/>    behold, O LORD, you know it altogether.<br/>[5] You hem me in, behind and before,<br/>    and lay your hand upon me.<br/>[6] Such knowledge is too wonderful for me;<br/>    it is high; I cannot attain it.<br/>[7] Where shall I go from your Spirit?<br/>    Or where shall I flee from your presence?<br/>[8] If I ascend to heaven, you are there!<br/>    If I make my bed in Sheol, you are there!<br/>[9] If I take the wings of the morning<br/>    and dwell in the uttermost parts of the sea,<br/>[10] even there your hand shall lead me,<br/>    and your right hand shall hold me.<br/>[11] If I say, \"Surely the darkness shall cover me,<br/>    and the light about me be night,\"<br/>[12] even the darkness is not dark to you;<br/>    the night is bright as the day,<br/>    for darkness is as light with you.<br/>[13] For you formed my inward parts;<br/>    you knitted me together in my mother's womb.<br/>[14] I praise you, for I am fearfully and wonderfully made.<br/>Wonderful are your works;<br/>    my soul knows it very well.<br/>[15] My frame was not hidden from you,<br/>when I was being made in secret,<br/>    intricately woven in the depths of the earth.<br/>[16] Your eyes saw my unformed substance;<br/>in your book were written, every one of them,<br/>    the days that were formed for me,<br/>    when as yet there was none of them.<br/>[17] How precious to me are your thoughts, O God!<br/>    How vast is the sum of them!<br/>[18] If I would count them, they are more than the sand.<br/>    I awake, and I am still with you.",
    "Isaiah 42:2-4: [2] He will not cry aloud or lift up his voice,<br/>    or make it heard in the street;<br/>[3] a bruised reed he will not break,<br/>    and a faintly burning wick he will not quench;<br/>    he will faithfully bring forth justice.<br/>[4] He will not grow faint or be discouraged<br/>    till he has established justice in the earth;<br/>    and the coastlands wait for his law.",
    "John 15:13: [13] Greater love has no one than this, that someone lay down his life for his friends."
  ];
  preservation = [
    "Isaiah 46:3-4: [3] \"Listen to me, O house of Jacob,<br/>    all the remnant of the house of Israel,<br/>who have been borne by me from before your birth,<br/>    carried from the womb;<br/>[4] even to your old age I am he,<br/>    and to gray hairs I will carry you.<br/>I have made, and I will bear;<br/>    I will carry and will save.",
    "John 6:37-40: [37] All that the Father gives me will come to me, and whoever comes to me I will never cast out. [38] For I have come down from heaven, not to do my own will but the will of him who sent me. [39] And this is the will of him who sent me, that I should lose nothing of all that he has given me, but raise it up on the last dy. [40] For this is the will of my Father, that everyone who looks on the Son and believes in him should have eternal life, and I will raise him up on the last day.\"",
    "John 10:27-29: [27] My sheep hear my voice, and I know them, and they follow me. [28] I give them eternal life, and they will never perish, and no one will snatch them out of my hand. [29] My Father, who has given them to me, is greater than all, and no one is able to snatch them out of the Father's hand.",
    "Romans 5:9-10: [9] Since, therefore, we have now been justified by his blood, much more shall we be saved by him from the wrath of God. [10] For if while we were enemies we were reconciled to God by the death of his Son, much more, now that we are reconciled, shall we be saved by his life.",
    "Romans 8:11: [11] If the Spirit of him who raised Jesus from the dead dwells in you, he who raised Christ Jesus from the dead will also give life to your mortal bodies through his Spirit who dwells in you.",
    "Romans 8:30-34: [30] And those whom he predestined he also called, and those whom he called he also justified, and those whom he justified he also glorified.<br/>[31] What then shall we say to these things? If God is for us, who can be against us? [32] He who did not spare his own Son but gave him up for us all, how will he not also with him graciously give us all things? [33] Who shall bring any charge against God's elect? It is God who justifies. [34] Who is to condemn? Christ Jesus is the one who died—more than that, who was raised—who is at the right hand of God, who indeed is interceding for us.",
    "Philippians 1:6: [6] And I am sure of this, that he who began a good work in you will bring it to completion at the day of Jesus Christ.",
    "Jude 1:24-25: [24] Now to him who is able to keep you from stumbling and to present you blameless before the presence of his glory with great joy, [25] to the only God, our Savior, through Jesus Christ our Lord, be glory, majesty, dominion, and authority, before all time and now and forever. Amen."
  ];
  evangelism = [
    "Matthew 28:18-20: [18] And Jesus came and said to them, \"All authority in heaven and on earth has been given to me. [19] Go therefore and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit, [20] teaching them to observe all that I have commanded you. And behold, I am with you always, to the end of the age.\"",
    "John 4:35-39: [35] Do you not say, ‘There are yet four months, then comes the harvest’? Look, I tell you, lift up your eyes, and see that the fields are white for harvest. [36] Already the one who reaps is receiving wages and gathering fruit for eternal life, so that sower and reaper may rejoice together. [37] For here the saying holds true, ‘One sows and another reaps.’ [38] I sent you to reap that for which you did not labor. Others have labored, and you have entered into their labor.\"<br/>[39] Many Samaritans from that town believed in him because of the woman's testimony, \"He told me all that I ever did.\"",
    "Romans 1:16: [16] For I am not ashamed of the gospel, for it is the power of God for salvation to everyone who believes, to the Jew first and also to the Greek.",
    "Colossians 4:2-6: [2] Continue steadfastly in prayer, being watchful in it with thanksgiving. [3] At the same time, pray also for us, that God may open to us a door for the word, to declare the mystery of Christ, on account of which I am in prison—[4] that I may make it clear, which is how I ought to speak.<br/>[5] Walk in wisdom toward outsiders, making the best use of the time. [6] Let your speech always be gracious, seasoned with salt, so that you may know how you ought to answer each person.",
    "1 Peter 3:15: [15] but in your hearts honor Christ the Lord as holy, always being prepared to make a defense to anyone who asks you for a reason for the hope that is in you; yet do it with gentleness and respect,"
  ];
  eternalLife = [
    "John 4:13-14: [13] Jesus said to her, “Everyone who drinks of this water will be thirsty again, [14] but whoever drinks of the water that I will give him will never be thirsty again. The water that I will give him will become in him a spring of water welling up to eternal life.”",
    "John 5:24-26: [24] Truly, truly, I say to you, whoever hears my word and believes him who sent me has eternal life. He does not come into judgment, but has passed from death to life.<br/>[25] “Truly, truly, I say to you, an hour is coming, and is now here, when the dead will hear the voice of the Son of God, and those who hear will live. [26] For as the Father has life in himself, so he has granted the Son also to have life in himself.",
    "John 6:47-51: [47] Truly, truly, I say to you, whoever believes has eternal life. [48] I am the bread of life. [49] Your fathers ate the manna in the wilderness, and they died. [50] This is the bread that comes down from heaven, so that one may eat of it and not die. [51] I am the living bread that came down from heaven. If anyone eats of this bread, he will live forever. And the bread that I will give for the life of the world is my flesh.”",
    "John 8:12: [12] Again Jesus spoke to them, saying, “I am the light of the world. Whoever follows me will not walk in darkness, but will have the light of life.”",
    "John 10:10: [10] The thief comes only to steal and kill and destroy. I came that they may have life and have it abundantly.",
    "John 11:25-26: [25] Jesus said to her, “I am the resurrection and the life. Whoever believes in me, though he die, yet shall he live, [26] and everyone who lives and believes in me shall never die. Do you believe this?”",
    "John 17:3: [3] And this is eternal life, that they know you, the only true God, and Jesus Christ whom you have sent.",
    "Romans 6:23: [23] For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord.",
    "1 John 5:11-13: [11] And this is the testimony, that God gave us eternal life, and this life is in his Son. [12] Whoever has the Son has life; whoever does not have the Son of God does not have life.<br/>[13] I write these things to you who believe in the name of the Son of God, that you may know that you have eternal life."
  ];
  newCreation = [
    "Isaiah 65:17-25: [17] “For behold, I create new heavens<br/>    and a new earth,<br/>and the former things shall not be remembered<br/>    or come into mind.<br/>[18] But be glad and rejoice forever<br/>    in that which I create;<br/>for behold, I create Jerusalem to be a joy,<br/>    and her people to be a gladness.<br/>[19] I will rejoice in Jerusalem<br/>    and be glad in my people;<br/>no more shall be heard in it the sound of weeping<br/>    and the cry of distress.<br/>[20] No more shall there be in it<br/>    an infant who lives but a few days,<br/>    or an old man who does not fill out his days,<br/>for the young man shall die a hundred years old,<br/>    and the sinner a hundred years old shall be accursed.<br/>[21] They shall build houses and inhabit them;<br/>    they shall plant vineyards and eat their fruit.<br/>[22] They shall not build and another inhabit;<br/>    they shall not plant and another eat;<br/>for like the days of a tree shall the days of my people be,<br/>    and my chosen shall long enjoy the work of their hands.<br/>[23] They shall not labor in vain<br/>    or bear children for calamity,<br/>for they shall be the offspring of the blessed of the LORD,<br/>    and their descendants with them.<br/>[24] Before they call I will answer;<br/>    while they are yet speaking I will hear.<br/>[25] The wolf and the lamb shall graze together;<br/>    the lion shall eat straw like the ox,<br/>    and dust shall be the serpent's food.<br/>They shall not hurt or destroy<br/>    in all my holy mountain,”<br/>    says the LORD.",
    "John 14:1-4: [1] “Let not your hearts be troubled. Believe in God; believe also in me. [2] In my Father's house are many rooms. If it were not so, would I have told you that I go to prepare a place for you? [3] And if I go and prepare a place for you, I will come again and will take you to myself, that where I am you may be also. [4] And you know the way to where I am going.”",
    "Romans 8:18-23: [18] For I consider that the sufferings of this present time are not worth comparing with the glory that is to be revealed to us. [19] For the creation waits with eager longing for the revealing of the sons of God. [20] For the creation was subjected to futility, not willingly, but because of him who subjected it, in hope [21] that the creation itself will be set free from its bondage to corruption and obtain the freedom of the glory of the children of God. [22] For we know that the whole creation has been groaning together in the pains of childbirth until now. [23] And not only the creation, but we ourselves, who have the firstfruits of the Spirit, groan inwardly as we wait eagerly for adoption as sons, the redemption of our bodies.",
    "1 Corinthians 15:51-57: [51] Behold! I tell you a mystery. We shall not all sleep, but we shall all be changed, [52] in a moment, in the twinkling of an eye, at the last trumpet. For the trumpet will sound, and the dead will be raised imperishable, and we shall be changed. [53] For this perishable body must put on the imperishable, and this mortal body must put on immortality. [54] When the perishable puts on the imperishable, and the mortal puts on immortality, then shall come to pass the saying that is written:<br/>“Death is swallowed up in victory.”<br/>[55] “O death, where is your victory?<br/>    O death, where is your sting?”<br/>[56] The sting of death is sin, and the power of sin is the law. [57] But thanks be to God, who gives us the victory through our Lord Jesus Christ.",
    "2 Corinthians 5:17: [17] Therefore, if anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come.",
    "Revelation 21:1-7: [1] Then I saw a new heaven and a new earth, for the first heaven and the first earth had passed away, and the sea was no more. [2] And I saw the holy city, new Jerusalem, coming down out of heaven from God, prepared as a bride adorned for her husband. [3] And I heard a loud voice from the throne saying, “Behold, the dwelling place of God is with man. He will dwell with them, and they will be his people, and God himself will be with them as their God. [4] He will wipe away every tear from their eyes, and death shall be no more, neither shall there be mourning, nor crying, nor pain anymore, for the former things have passed away.”<br/>[5] And he who was seated on the throne said, “Behold, I am making all things new.” Also he said, “Write this down, for these words are trustworthy and true.” [6] And he said to me, “It is done! I am the Alpha and the Omega, the beginning and the end. To the thirsty I will give from the spring of the water of life without payment. [7] The one who conquers will have this heritage, and I will be his God and he will be my son.",
    "Revelation 22:1-5: [1] Then the angel showed me the river of the water of life, bright as crystal, flowing from the throne of God and of the Lamb [2] through the middle of the street of the city; also, on either side of the river, the tree of life with its twelve kinds of fruit, yielding its fruit each month. The leaves of the tree were for the healing of the nations. [3] No longer will there be anything accursed, but the throne of God and of the Lamb will be in it, and his servants will worship him. [4] They will see his face, and his name will be on their foreheads. [5] And night will be no more. They will need no light of lamp or sun, for the Lord God will be their light, and they will reign forever and ever."
  ];
  satisfaction = [
    "Psalm 16: A Miktam of David.<br/>[1] Preserve me, O God, for in you I take refuge.<br/>[2] I say to the LORD, “You are my Lord;<br/>    I have no good apart from you.”<br/>[3] As for the saints in the land, they are the excellent ones,<br/>    in whom is all my delight.<br/>[4] The sorrows of those who run after another god shall multiply;<br/>    their drink offerings of blood I will not pour out<br/>    or take their names on my lips.<br/>[5] The LORD is my chosen portion and my cup;<br/>    you hold my lot.<br/>[6] The lines have fallen for me in pleasant places;<br/>    indeed, I have a beautiful inheritance.<br/>[7] I bless the LORD who gives me counsel;<br/>    in the night also my heart instructs me.<br/>[8] I have set the LORD always before me;<br/>    because he is at my right hand, I shall not be shaken.<br/>[9] Therefore my heart is glad, and my whole being rejoices;<br/>    my flesh also dwells secure.<br/>[10] For you will not abandon my soul to Sheol,<br/>    or let your holy one see corruption.<br/>[11] You make known to me the path of life;<br/>    in your presence there is fullness of joy;<br/>    at your right hand are pleasures forevermore.",
    "Psalm 19:7-10: [7] The law of the LORD is perfect,<br/>    reviving the soul;<br/>the testimony of the LORD is sure,<br/>    making wise the simple;<br/>[8] the precepts of the LORD are right,<br/>    rejoicing the heart;<br/>the commandment of the LORD is pure,<br/>    enlightening the eyes;<br/>[9] the fear of the LORD is clean,<br/>    enduring forever;<br/>the rules of the LORD are true,<br/>    and righteous altogether.<br/>[10] More to be desired are they than gold,<br/>    even much fine gold;<br/>sweeter also than honey<br/>    and drippings of the honeycomb.",
    "Psalm 23: A Psalm of David.<br/>[1] The LORD is my shepherd; I shall not want.<br/>[2]     He makes me lie down in green pastures.<br/>He leads me beside still waters.<br/>[3]     He restores my soul.<br/>He leads me in paths of righteousness<br/>    for his name's sake.<br/>[4] Even though I walk through the valley of the shadow of death,<br/>    I will fear no evil,<br/>for you are with me;<br/>    your rod and your staff,<br/>    they comfort me.<br/>[5] You prepare a table before me<br/>    in the presence of my enemies;<br/>you anoint my head with oil;<br/>    my cup overflows.<br/>[6] Surely goodness and mercy shall follow me<br/>    all the days of my life,<br/>and I shall dwell in the house of the LORD<br/>    forever.",
    "Psalm 63: A Psalm of David, when he was in the wilderness of Judah.<br/>[1] O God, you are my God; earnestly I seek you;<br/>    my soul thirsts for you;<br/>my flesh faints for you,<br/>    as in a dry and weary land where there is no water.<br/>[2] So I have looked upon you in the sanctuary,<br/>    beholding your power and glory.<br/>[3] Because your steadfast love is better than life,<br/>    my lips will praise you.<br/>[4] So I will bless you as long as I live;<br/>    in your name I will lift up my hands.<br/>[5] My soul will be satisfied as with fat and rich food,<br/>    and my mouth will praise you with joyful lips,<br/>[6] when I remember you upon my bed,<br/>    and meditate on you in the watches of the night;<br/>[7] for you have been my help,<br/>    and in the shadow of your wings I will sing for joy.<br/>[8] My soul clings to you;<br/>    your right hand upholds me.<br/>[9] But those who seek to destroy my life<br/>    shall go down into the depths of the earth;<br/>[10] they shall be given over to the power of the sword;<br/>    they shall be a portion for jackals.<br/>[11] But the king shall rejoice in God;<br/>    all who swear by him shall exult,<br/>    for the mouths of liars will be stopped.",
    "Isaiah 55:1-3: [1] “Come, everyone who thirsts,<br/>    come to the waters;<br/>and he who has no money,<br/>    come, buy and eat!<br/>Come, buy wine and milk<br/>    without money and without price.<br/>[2] Why do you spend your money for that which is not bread,<br/>    and your labor for that which does not satisfy?<br/>Listen diligently to me, and eat what is good,<br/>    and delight yourselves in rich food.<br/>[3] Incline your ear, and come to me;<br/>    hear, that your soul may live;<br/>and I will make with you an everlasting covenant,<br/>    my steadfast, sure love for David.",
    "Ezekiel 34:11-16: [11] “For thus says the Lord GOD: Behold, I, I myself will search for my sheep and will seek them out. [12] As a shepherd seeks out his flock when he is among his sheep that have been scattered, so will I seek out my sheep, and I will rescue them from all places where they have been scattered on a day of clouds and thick darkness. [13] And I will bring them out from the peoples and gather them from the countries, and will bring them into their own land. And I will feed them on the mountains of Israel, by the ravines, and in all the inhabited places of the country. [14] I will feed them with good pasture, and on the mountain heights of Israel shall be their grazing land. There they shall lie down in good grazing land, and on rich pasture they shall feed on the mountains of Israel. [15] I myself will be the shepherd of my sheep, and I myself will make them lie down, declares the Lord GOD. [16] I will seek the lost, and I will bring back the strayed, and I will bind up the injured, and I will strengthen the weak, and the fat and the strong I will destroy. I will feed them in justice.",
    "John 6:35: [35] Jesus said to them, “I am the bread of life; whoever comes to me shall not hunger, and whoever believes in me shall never thirst.",
    "John 7:37-38: [37] On the last day of the feast, the great day, Jesus stood up and cried out, “If anyone thirsts, let him come to me and drink. [38] Whoever believes in me, as the Scripture has said, ‘Out of his heart will flow rivers of living water.’”",
    "Philippians 4:19: [19] And my God will supply every need of yours according to his riches in glory in Christ Jesus."
  ];
  family = [
    "Psalm 127: A Song of Ascents. Of Solomon.<br/>[1] Unless the LORD builds the house,<br/>    those who build it labor in vain.<br/>Unless the LORD watches over the city,<br/>    the watchman stays awake in vain.<br/>[2] It is in vain that you rise up early<br/>    and go late to rest,<br/>eating the bread of anxious toil;<br/>    for he gives to his beloved sleep.<br/>[3] Behold, children are a heritage from the LORD,<br/>    the fruit of the womb a reward.<br/>[4] Like arrows in the hand of a warrior<br/>    are the children of one's youth.<br/>[5] Blessed is the man<br/>    who fills his quiver with them!<br/>He shall not be put to shame<br/>    when he speaks with his enemies in the gate.",
    "Psalm 128: A Song of Ascents.<br/>[1] Blessed is everyone who fears the LORD,<br/>    who walks in his ways!<br/>[2] You shall eat the fruit of the labor of your hands;<br/>    you shall be blessed, and it shall be well with you.<br/>[3] Your wife will be like a fruitful vine<br/>    within your house;<br/>your children will be like olive shoots<br/>    around your table.<br/>[4] Behold, thus shall the man be blessed<br/>    who fears the LORD.<br/>[5] The LORD bless you from Zion!<br/>    May you see the prosperity of Jerusalem<br/>    all the days of your life!<br/>[6] May you see your children's children!<br/>    Peace be upon Israel!",
    "Proverbs 17:17: [17] A friend loves at all times,<br/>    and a brother is born for adversity.",
    "Ecclesiastes 4:12: [12] And though a man might prevail against one who is alone, two will withstand him—a threefold cord is not quickly broken.",
    "Isaiah 56:3-5: [3] Let not the foreigner who has joined himself to the LORD say,<br/>    “The LORD will surely separate me from his people”;<br/>and let not the eunuch say,<br/>    “Behold, I am a dry tree.”<br/>[4] For thus says the LORD:<br/>“To the eunuchs who keep my Sabbaths,<br/>    who choose the things that please me<br/>    and hold fast my covenant,<br/>[5] I will give in my house and within my walls<br/>    a monument and a name<br/>    better than sons and daughters;<br/>I will give them an everlasting name<br/>    that shall not be cut off.",
    "Ephesians 5:22-33: [22] Wives, submit to your own husbands, as to the Lord. [23] For the husband is the head of the wife even as Christ is the head of the church, his body, and is himself its Savior. [24] Now as the church submits to Christ, so also wives should submit in everything to their husbands.<br/>[25] Husbands, love your wives, as Christ loved the church and gave himself up for her, [26] that he might sanctify her, having cleansed her by the washing of water with the word, [27] so that he might present the church to himself in splendor, without spot or wrinkle or any such thing, that she might be holy and without blemish. [28] In the same way husbands should love their wives as their own bodies. He who loves his wife loves himself. [29] For no one ever hated his own flesh, but nourishes and cherishes it, just as Christ does the church, [30] because we are members of his body. [31] “Therefore a man shall leave his father and mother and hold fast to his wife, and the two shall become one flesh.” [32] This mystery is profound, and I am saying that it refers to Christ and the church. [33] However, let each one of you love his wife as himself, and let the wife see that she respects her husband."
  ];
  money = [
    "Psalm 62:10: [10] Put no trust in extortion;<br/>    set no vain hopes on robbery;<br/>    if riches increase, set not your heart on them.",
    "1 Timothy 6:6-10: [6] But godliness with contentment is great gain, [7] for we brought nothing into the world, and we cannot take anything out of the world. [8] But if we have food and clothing, with these we will be content. [9] But those who desire to be rich fall into temptation, into a snare, into many senseless and harmful desires that plunge people into ruin and destruction. [10] For the love of money is a root of all kinds of evils. It is through this craving that some have wandered away from the faith and pierced themselves with many pangs.",
    "1 Timothy 6:17-19: [17] As for the rich in this present age, charge them not to be haughty, nor to set their hopes on the uncertainty of riches, but on God, who richly provides us with everything to enjoy. [18] They are to do good, to be rich in good works, to be generous and ready to share, [19] thus storing up treasure for themselves as a good foundation for the future, so that they may take hold of that which is truly life.",
    "Hebrews 13:5-6: [5] Keep your life free from love of money, and be content with what you have, for he has said, “I will never leave you nor forsake you.” [6] So we can confidently say,<br/>“The Lord is my helper;<br/>    I will not fear;<br/>what can man do to me?”",
    "1 John 2:15-17: [15] Do not love the world or the things in the world. If anyone loves the world, the love of the Father is not in him. [16] For all that is in the world—the desires of the flesh and the desires of the eyes and pride of life—is not from the Father but is from the world. [17] And the world is passing away along with its desires, but whoever does the will of God abides forever.",
    "1 John 3:17: [17] But if anyone has the world's goods and sees his brother in need, yet closes his heart against him, how does God's love abide in him?"
  ];

  constructor(public navCtrl: NavController,
              public navParams: NavParams,
              private storage: Storage,
              public events: Events,
              private actionSheetCtrl: ActionSheetController,
              private toastCtrl: ToastController) {
  }

  updateTopic() {
    console.log("topic " + this.topic);
    if (this.topic == "Salvation") this.passages = this.salvation;
    else if (this.topic == "Grace") this.passages = this.grace;
    else if (this.topic == "Confession") this.passages = this.confession;
    else if (this.topic == "Suffering") this.passages = this.suffering;
    else if (this.topic == "Motivation to holiness") this.passages = this.motivationToHoliness;
    else if (this.topic == "Adoption") this.passages = this.adoption;
    else if (this.topic == "Trusting God") this.passages = this.trustingGod;
    else if (this.topic == "The greatness of God") this.passages = this.theGreatnessOfGod;
    else if (this.topic == "The kindness of God") this.passages = this.theKindnessOfGod;
    else if (this.topic == "Preservation") this.passages = this.preservation;
    else if (this.topic == "Evangelism") this.passages = this.evangelism;
    else if (this.topic == "Eternal life") this.passages = this.eternalLife;
    else if (this.topic == "New creation") this.passages = this.newCreation;
    else if (this.topic == "Satisfaction") this.passages = this.satisfaction;
    else if (this.topic == "Family") this.passages = this.family;
    else if (this.topic == "Money") this.passages = this.money;
  }

  selectPassage = (passage) => {
    var splitIndex = passage.indexOf(": ");
    var reference = passage.substring(0, splitIndex);
    var text = passage.substring(splitIndex + 2);
    //todo fix poetry - we lose indentation
    const actionSheet = this.actionSheetCtrl.create({
      title: reference,
      subTitle: text.replace(/<br\/>/g, "\n"),
      buttons: [
        {
          text: 'Add to my list',
          handler: () => {
            this.storage.get(reference).then((passage2) => {
              // First check if passage is added already, or is a folder name
              if (passage2 != null) {
                let toast = this.toastCtrl.create({
                  message: reference + ' already added',
                  duration: 2000,
                  position: 'bottom'
                });
                toast.present();
                return;
              }

              this.storage.get("Top Level Folder").then((folder) => {
                if (folder == null) {
                  folder = [];
                }

                folder.push({ reference: reference, date: moment().format("MM[/]DD[/]YY"), timestamp: moment.now() });
                this.storage.set("Top Level Folder", folder);
                this.storage.set(reference, text.replace(/<br\/>/g, "#")).then( () => {
                  this.events.publish('passagesChanged');
                  let toast = this.toastCtrl.create({
                    message: reference + ' added successfully',
                    duration: 2000,
                    position: 'bottom'
                  });
                  toast.present();

                });
              });
            });
          }
        },{
          text: 'Cancel',
          role: 'cancel'
        }
      ]
    });
    actionSheet.present();
  }

  ionViewDidLoad() {
    console.log('ionViewDidLoad SuggestionsPage');
  }
}
